# Generated by Django 5.2.2 on 2025-06-08 14:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inscripcion',
            old_name='email_participante',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='lugar',
            old_name='nombre_lugar',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_fin',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='fecha_inicio',
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='fecha_inscripcion',
        ),
        migrations.RemoveField(
            model_name='lugar',
            name='capacidad',
        ),
        migrations.RemoveField(
            model_name='organizador',
            name='telefono',
        ),
        migrations.AddField(
            model_name='evento',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 6, 8)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='evento',
            name='hora',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lugar',
            name='direccion',
            field=models.CharField(max_length=255),
        ),
    ]
